# Generated by Django 3.1.7 on 2021-04-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Group',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('age', models.CharField(max_length=100)),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Ammenities',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('ammenities_list', models.TextField()),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('policy_title', models.TextField(default='')),
                ('policy_text', models.TextField(default='')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('class_topic', models.CharField(max_length=200)),
                ('class_description', models.TextField(blank=True, null=True)),
                ('class_image', models.FileField(blank=True, null=True, upload_to='course')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.CharField(default=0, max_length=200)),
                ('no_of_participants', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('All Levels', 'All Levels'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Select Level', max_length=100)),
                ('class_expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.TextField()),
                ('course_image', models.FileField(blank=True, null=True, upload_to='course')),
                ('start_time', models.TimeField(default='10:00:00')),
                ('end_time', models.TimeField(default='11:00:00')),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('no_of_participants', models.CharField(default='', max_length=20)),
                ('course_price', models.FloatField(default='0')),
                ('level', models.CharField(choices=[('All Levels', 'All Levels'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Select Level', max_length=100)),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='GymProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('gym_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=12)),
                ('about', models.TextField()),
                ('gender_criteria', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=50)),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='GymTime',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('time_text', models.CharField(default='', max_length=200)),
                ('open_at', models.TimeField()),
                ('close_at', models.TimeField()),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('help_text', models.TextField()),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('occasion', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('instructor_specializaton', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('gym_location', models.CharField(blank=True, max_length=500, null=True)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('day', models.CharField(max_length=50)),
                ('int_day', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Weekdays',
                'ordering': ['created_at'],
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('transaction_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('transaction_amount', models.CharField(blank=True, max_length=12, null=True)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quaterly', 'Quaterly'), ('Yearly', 'Yearly'), ('One Time', 'One Time')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=50, null=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('package_name', models.CharField(max_length=250)),
                ('package_description', models.TextField(blank=True, default='', null=True)),
                ('package_price', models.CharField(max_length=10)),
                ('class_passes', models.CharField(default='', max_length=10)),
                ('package_duration', models.CharField(blank=True, max_length=10, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.gymprofile')),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('img', models.FileField(null=True, upload_to='online')),
                ('date', models.DateField()),
                ('Type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('max_strength', models.CharField(max_length=50, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
                ('online_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymprofile.instructor')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('membership_title', models.CharField(max_length=250)),
                ('membership_description', models.TextField()),
                ('membership_duration', models.CharField(max_length=10)),
                ('membership_amount', models.CharField(max_length=100)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
                ('membership_age_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group')),
                ('select_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.location')),
            ],
            bases=('base.basemodel',),
        ),
    ]
