# Generated by Django 3.1.7 on 2021-04-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile'),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='age_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group'),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.location'),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='gym_timings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymtime'),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='opening_days',
            field=models.ManyToManyField(to='gymprofile.Weekdays'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_scheduled_on',
            field=models.ManyToManyField(to='gymprofile.Weekdays'),
        ),
        migrations.AddField(
            model_name='course',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymprofile.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='select_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.location'),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_scheduled_on',
            field=models.ManyToManyField(to='gymprofile.Weekdays'),
        ),
        migrations.AddField(
            model_name='classes',
            name='classes_age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group'),
        ),
        migrations.AddField(
            model_name='classes',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile'),
        ),
        migrations.AddField(
            model_name='classes',
            name='instructor_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymprofile.instructor'),
        ),
        migrations.AddField(
            model_name='classes',
            name='select_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.location'),
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile'),
        ),
        migrations.AddField(
            model_name='ammenities',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile'),
        ),
    ]
