# Generated by Django 3.1.7 on 2021-04-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0002_auto_20210406_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='gym',
        ),
    ]
