# Generated by Django 3.1.7 on 2021-04-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0003_remove_location_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='city',
            field=models.ManyToManyField(blank=True, to='gymprofile.Location'),
        ),
    ]
