# Generated by Django 3.1.7 on 2021-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0004_auto_20210412_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ammenities',
            old_name='ammenities_list',
            new_name='ammenities_detail',
        ),
        migrations.AddField(
            model_name='ammenities',
            name='ammenities_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
