# Generated by Django 3.2 on 2021-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0005_auto_20210419_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_address',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='course_address',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='course',
            name='course_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default=True, max_length=50),
        ),
    ]
