# Generated by Django 3.2 on 2021-07-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('gymprofile', '0008_delete_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('membership_title', models.CharField(max_length=250)),
                ('membership_description', models.TextField()),
                ('membership_duration', models.CharField(max_length=10)),
                ('membership_amount', models.CharField(max_length=100)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
                ('membership_age_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group')),
                ('select_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.location')),
            ],
            bases=('base.basemodel',),
        ),
    ]
