# Generated by Django 3.2 on 2021-08-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0009_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymprofile',
            name='gym_image',
            field=models.FileField(blank=True, null=True, upload_to='Gymimage'),
        ),
    ]
