# Generated by Django 3.2 on 2021-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0010_gymprofile_gym_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymprofile',
            name='gym_theme',
            field=models.CharField(default='red', max_length=255),
        ),
    ]
