# Generated by Django 3.2 on 2021-08-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0011_gymprofile_gym_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymprofile',
            name='gym_theme',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('brown', 'brown'), ('orange', 'orange'), ('pink', 'pink'), ('blue', 'blue'), ('lightgreen', 'lightgreen'), ('yelolow', 'yellow'), ('purple', 'purple')], default='red', max_length=255),
        ),
    ]
