# Generated by Django 3.2 on 2021-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0014_auto_20210812_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_price',
            field=models.IntegerField(default=5),
        ),
    ]
