# Generated by Django 3.2 on 2021-08-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0015_classes_class_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seat_available',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
