# Generated by Django 3.2 on 2021-08-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0016_course_seat_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='level',
            field=models.CharField(choices=[('All', 'All'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Select Level', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('All', 'All'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Select Level', max_length=100),
        ),
    ]
