# Generated by Django 3.2 on 2021-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0017_auto_20210818_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='seat_available',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
