# Generated by Django 3.2 on 2021-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='history_image',
            field=models.FileField(blank=True, null=True, upload_to='userhisytory'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='history_price',
            field=models.FloatField(default='0'),
        ),
    ]
