# Generated by Django 3.2 on 2021-07-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210714_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
