# Generated by Django 3.2 on 2021-07-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0009_membership'),
        ('user', '0005_remove_subscription_membership_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='membership_purchased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymprofile.membership'),
        ),
    ]
