# Generated by Django 3.2 on 2021-08-07 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0012_alter_gymprofile_gym_theme'),
        ('base', '0001_initial'),
        ('user', '0006_subscription_membership_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('booked_date', models.DateField(null=True)),
                ('class_passes', models.CharField(blank=True, max_length=12, null=True)),
                ('seat_available', models.CharField(blank=True, max_length=12, null=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
                ('select_courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.course')),
                ('select_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('base.basemodel',),
        ),
    ]
