# Generated by Django 3.2 on 2021-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='passes',
            field=models.IntegerField(default=0),
        ),
    ]
