# Generated by Django 3.2 on 2021-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_subscription_passes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='for_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='type',
            field=models.CharField(default='History', max_length=255),
        ),
    ]
