# Generated by Django 3.2 on 2021-08-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210812_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='booked_date',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='class_passes',
        ),
    ]
