# Generated by Django 3.2 on 2021-09-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_usercourse_seat_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='history_image',
            field=models.FileField(blank=True, null=True, upload_to='userhistory'),
        ),
    ]
