# Generated by Django 3.2 on 2021-09-28 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0019_alter_gymprofile_gym_theme'),
        ('base', '0001_initial'),
        ('user', '0012_alter_userhistory_history_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('title', models.TextField()),
                ('descricription', models.TextField()),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='FavouriteGym',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('favourite_gym_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('title', models.TextField()),
                ('Advertisement_class', models.CharField(max_length=100, null=True)),
                ('action', models.TextField(null=True)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
    ]
