# Generated by Django 3.2 on 2021-09-29 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymprofile', '0019_alter_gymprofile_gym_theme'),
        ('user', '0013_advertisement_favouritegym_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='Advertisement_class',
        ),
        migrations.RemoveField(
            model_name='news',
            name='descricription',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertized_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.classes'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
